"""Build bt/voice_catalog.py from Piper's published voice list (rhasspy/piper-voices voices.json).

Keeps single-speaker voices; per language, medium/high quality voices, falling back to low/x_low
only for languages that have nothing better. Sizes come from the list itself.
Run:  .venv\\Scripts\\python.exe tools\\make_voice_catalog.py
"""
import json
import os
import ssl
import urllib.request

URL = "https://huggingface.co/rhasspy/piper-voices/resolve/main/voices.json"
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "bt", "voice_catalog.py")
GOOD = ("medium", "high")


def main():
    import certifi
    ctx = ssl.create_default_context(cafile=certifi.where())
    ctx.verify_flags &= ~ssl.VERIFY_X509_STRICT
    req = urllib.request.Request(URL, headers={"User-Agent": "BookTalker"})
    data = json.load(urllib.request.urlopen(req, context=ctx, timeout=60))
    voices = [v for v in data.values() if v["num_speakers"] == 1]
    good_langs = {v["language"]["family"] for v in voices if v["quality"] in GOOD}
    rows = []
    for v in sorted(voices, key=lambda v: v["key"]):
        fam = v["language"]["family"]
        if v["quality"] not in GOOD and fam in good_langs:
            continue
        size = sum(f["size_bytes"] for f in v["files"].values())
        rows.append((v["key"], fam, v["language"]["country_english"], v["quality"], round(size / 1e6)))
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write('"""Every Piper voice BookTalker offers (generated by tools/make_voice_catalog.py — do not edit).\n\n'
                'stem -> (language, country, quality, download size in MB)\n"""\n')
        f.write("CATALOG = {\n")
        for stem, fam, country, quality, mb in rows:
            f.write(f"    {stem!r}: ({fam!r}, {country!r}, {quality!r}, {mb}),\n")
        f.write("}\n")
    print(len(rows), "voices in", len({r[1] for r in rows}), "languages ->", OUT)


if __name__ == "__main__":
    main()
